python main_CMNIST.py --color_var 0.0
python main_CMNIST.py --color_var 0.001 
python main_CMNIST.py --color_var 0.002
python main_CMNIST.py --color_var 0.003
python main_CMNIST.py --color_var 0.004
python main_CMNIST.py --color_var 0.005
python main_CMNIST.py --color_var 0.006
python main_CMNIST.py --color_var 0.007
python main_CMNIST.py --color_var 0.008
python main_CMNIST.py --color_var 0.009
python main_CMNIST.py --color_var 0.01
python main_CMNIST.py --color_var 0.011 
python main_CMNIST.py --color_var 0.012
python main_CMNIST.py --color_var 0.013
python main_CMNIST.py --color_var 0.014
python main_CMNIST.py --color_var 0.015
python main_CMNIST.py --color_var 0.016
python main_CMNIST.py --color_var 0.017
python main_CMNIST.py --color_var 0.018
python main_CMNIST.py --color_var 0.019
python main_CMNIST.py --color_var 0.02
python main_CMNIST.py --color_var 0.025 
python main_CMNIST.py --color_var 0.03
python main_CMNIST.py --color_var 0.035 
python main_CMNIST.py --color_var 0.04
python main_CMNIST.py --color_var 0.045 
python main_CMNIST.py --color_var 0.05