python EnD_rebias_mnist_sweep_our.py --color_var 0.0
python EnD_rebias_mnist_sweep_our.py --color_var 0.001 
python EnD_rebias_mnist_sweep_our.py --color_var 0.002
python EnD_rebias_mnist_sweep_our.py --color_var 0.003
python EnD_rebias_mnist_sweep_our.py --color_var 0.004
python EnD_rebias_mnist_sweep_our.py --color_var 0.005
python EnD_rebias_mnist_sweep_our.py --color_var 0.006
python EnD_rebias_mnist_sweep_our.py --color_var 0.007
python EnD_rebias_mnist_sweep_our.py --color_var 0.008
python EnD_rebias_mnist_sweep_our.py --color_var 0.009
python EnD_rebias_mnist_sweep_our.py --color_var 0.01
python EnD_rebias_mnist_sweep_our.py --color_var 0.011 
python EnD_rebias_mnist_sweep_our.py --color_var 0.012
python EnD_rebias_mnist_sweep_our.py --color_var 0.013
python EnD_rebias_mnist_sweep_our.py --color_var 0.014
python EnD_rebias_mnist_sweep_our.py --color_var 0.015
python EnD_rebias_mnist_sweep_our.py --color_var 0.016
python EnD_rebias_mnist_sweep_our.py --color_var 0.017
python EnD_rebias_mnist_sweep_our.py --color_var 0.018
python EnD_rebias_mnist_sweep_our.py --color_var 0.019
python EnD_rebias_mnist_sweep_our.py --color_var 0.02
python EnD_rebias_mnist_sweep_our.py --color_var 0.025 
python EnD_rebias_mnist_sweep_our.py --color_var 0.03
python EnD_rebias_mnist_sweep_our.py --color_var 0.035 
python EnD_rebias_mnist_sweep_our.py --color_var 0.04
python EnD_rebias_mnist_sweep_our.py --color_var 0.045 
python EnD_rebias_mnist_sweep_our.py --color_var 0.05